import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Meetai-authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="bg-muted flex min-h-svh flex-col items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm md:max-w-xl">{children}</div>
    </div>
  );
}
